### ISSUE TITLE
Remove Guestful support

### ISSUE THREAD

**Issue by cristianfrumusanu** [pixelgrade/wp-job-manager-booking-services#1]
```Guestful has been acquired and, as a result of focusing on other services, we had to terminate the reservation service as of April 2016```

http://guestful.com

**Comment by nishasharma18** [comment]
Hi,

I used this plugin to my website using listify theme but when im trying to add service and resurva url , getting an error: Cannot use object of type WP_Post as array in /public_html/wp-content/plugins/wp-job-manager-booking-services-master/wp-job-manager-booking-services.php on line 190

can you help me to resolve this error.

**Comment by vladolaru** [comment]
@nishasharma18 I have fixed the issue. Can you get the latest version and tell me if everything is ok now?

**Comment by nishasharma18** [comment]
I tried with latest version and after fillign i have submitted it without editing again and submitted successfully. But when tried to edit got as error:

Warning: trim() expects parameter 1 to be string, array given in /public_html/wp-content/plugins/wp-job-manager-booking-services-master/wp-job-manager-booking-services.php on line 171

**Comment by nishasharma18** [comment]
Can you please check and help me to get this plugin work fine
